/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.resource.IResourceDescription;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.FilteringScope;

import com.google.inject.Inject;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DOMLScopeProvider extends AbstractDOMLScopeProvider {

	@Inject
	IResourceDescription.Manager mgr;
		
	@Override
	public IScope getScope(EObject context, EReference reference) {
		
		EObject root = EcoreUtil2.getRootContainer(context);
		return new FilteringScope(super.getScope(context, reference), (s) -> {
			EObject inneroot = EcoreUtil2.getRootContainer(s.getEObjectOrProxy());
			return root.equals(inneroot);
		});
	}

}
