/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DOMLScopeProvider extends AbstractDOMLScopeProvider {

}
