/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.piacere.dsl.rMDF.RMDFModel

@ExtendWith(InjectionExtension)
@InjectWith(RMDFInjectorProvider)
class RMDFParsingTest {
	
	@Inject
	extension ParseHelper<RMDFModel> parseHelper
	
	@Test
	def void fileExtension() {
		Assertions.assertEquals('rmdf', parseHelper.fileExtension)
	}
	
	@Test
	def void loadModel() {
		val parse = parseHelper.parse('''
			metadata:
			  _version: '0.0.1'
		''')
		Assertions.assertNotNull(parse)
		val errors = parse.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}	
	
	@Test
	def void provider() {
		val provider = parseHelper.parse('''
			provider:
			  alias: azure
			  features:
			    subscription_id:
			      type: String
			    tenant_id:
			      type: String
		''')
		Assertions.assertNotNull(provider)
		Assertions.assertEquals('azure', provider.provider.name)
		Assertions.assertEquals(2, provider.provider.features.size)
	}
	
}
