/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.piacere.dsl.RMDFRuntimeModule;
import org.piacere.dsl.RMDFStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RMDFIdeSetup extends RMDFStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RMDFRuntimeModule(), new RMDFIdeModule()));
	}
	
}
