/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "org.piacere.dsl.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String ProviderTemplate_Label;
	public static String ProviderTemplate_Description;
	public static String NodeTypeTemplate_Label;
	public static String NodeTypeTemplate_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}

	private Messages() {
	}
}
