/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.doml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DOMLStandaloneSetup extends DOMLStandaloneSetupGenerated {

	public static void doSetup() {
		new DOMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
