/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.piacere.dsl.DOMLRuntimeModule;
import org.piacere.dsl.DOMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DOMLIdeSetup extends DOMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DOMLRuntimeModule(), new DOMLIdeModule()));
	}
	
}
