/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DOMLUiModule extends AbstractDOMLUiModule {

	public DOMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
