/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.piacere.dsl.rMDF.CDataTypes;
import org.piacere.dsl.rMDF.CImports;
import org.piacere.dsl.rMDF.CMetadata;
import org.piacere.dsl.rMDF.CNodeTypes;

import com.google.inject.Inject;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class RMDFLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public RMDFLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
//	String text(Greeting ele) {
//		return "A greeting to " + ele.getName();
//	}
//
//	String image(Greeting ele) {
//		return "Greeting.gif";
//	}
	
	String text(CMetadata ele) {
		return "metadata";
	}
	
	String text(CImports ele) {
		return "imports";
	}
	
	String text(CDataTypes ele) {
		return "data_types";
	}
	
	String text(CNodeTypes ele) {
		return "node_types";
	}
}
