/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.piacere.dsl.parser.antlr.internal.InternalDOMLParser;

public class DOMLTokenSource extends AbstractIndentationTokenSource {

	public DOMLTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalDOMLParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalDOMLParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalDOMLParser.RULE_END;
	}

}
