/*
 * generated by Xtext 2.25.0
 */
package org.piacere.dsl.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.piacere.dsl.parser.antlr.internal.InternalRMDFParser;

public class RMDFTokenSource extends AbstractIndentationTokenSource {

	public RMDFTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalRMDFParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalRMDFParser.RULE_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalRMDFParser.RULE_END;
	}

}
